### ISSUE TITLE
Focus right function is dated!

### ISSUE THREAD

**Issue by etherbiswas** [luisrodrigues154/dwm-directionalfocus#3]
The focus right function doesnt work anymore. Do you plan on using dwm in the future? Should open another pr?

**Comment by luisrodrigues154** [comment]
Seems that the structure from the Monitor changed from the time it was developed! Checking the source code you likely have to swap the "gapp" variables by "m*" correspondent variables.

Check this source code here: https://git.suckless.org/dwm/file/dwm.c.html (line 120, Monitor struct definition).

I might be coming back to dwm soon, so i might fix this. in The meantime, i'll close this. 

Feel free to send the PR if you want (i have notifications off for PRs for some reason, my appologies)
